apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-private-cluster
  region: ap-south-1

vpc:
  subnets:
    private:
      ap-south-1a: { id: subnet-0b7103d59c70ad17f }
      ap-south-1b: { id: subnet-03626c1802a76636f }
      ap-south-1c: { id: subnet-0dd0a66ab031b8798 }
    public:
      ap-south-1a: { id: subnet-06c64967a809c8e2d }
      ap-south-1b: { id: subnet-0a13312918e03e98c }
      ap-south-1c: { id: subnet-0b8725aa4811ab859 }

  clusterEndpoints:
    publicAccess: false
    privateAccess: true

nodeGroups:
  - name: ng-private
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    privateNetworking: true
    subnets:
      - subnet-0b7103d59c70ad17f
      - subnet-03626c1802a76636f
      - subnet-0dd0a66ab031b8798
    ssh:
      allow: true
  - name: ng-private-2
    instanceType: t3.medium
    labels: { app: critical }
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    privateNetworking: true
    subnets:
      - subnet-0b7103d59c70ad17f
      - subnet-03626c1802a76636f
      - subnet-0dd0a66ab031b8798
    taints:
      - key: app
        value: "critical"
        effect: NoSchedule
